/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignonRouteImport } from './routes/signon'
import { Route as BankingRouteImport } from './routes/banking'
import { Route as IndexRouteImport } from './routes/index'

const SignonRoute = SignonRouteImport.update({
  id: '/signon',
  path: '/signon',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingRoute = BankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banking': typeof BankingRoute
  '/signon': typeof SignonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banking': typeof BankingRoute
  '/signon': typeof SignonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banking': typeof BankingRoute
  '/signon': typeof SignonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/banking' | '/signon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/banking' | '/signon'
  id: '__root__' | '/' | '/banking' | '/signon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankingRoute: typeof BankingRoute
  SignonRoute: typeof SignonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signon': {
      id: '/signon'
      path: '/signon'
      fullPath: '/signon'
      preLoaderRoute: typeof SignonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking': {
      id: '/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof BankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankingRoute: BankingRoute,
  SignonRoute: SignonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
